language: node_js
node_js:
  - "0.11"
  - "0.12"
  - "4.0"
  - "4.1"
  - "4.2"
  - "5.1"
  - "5.0"
  - "iojs"
script: "npm run-script test-travis"
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"
